runtime: go114

main: ./server

includes:
  - fax.yaml

env_variables:
  BUCKET_NAME: "fax-machine-295219.appspot.com"
  GCS_CREDENTIALS: "gcs_credentials.json"

instance_class: B1

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

