runtime: go114

main: ./server

includes:
  - fax.yaml
  - payment.yaml

env_variables:
  BUCKET_NAME: "fax-machine-295219.appspot.com"
  GCS_CREDENTIALS: "gcs_credentials.json"
  GIN_MODE: "release"
  IS_APPENGINE: "true"

instance_class: B1

# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

basic_scaling:
  max_instances: 1
  idle_timeout: 5m
